FROM public.ecr.aws/lambda/python:3.12.2024.08.09.13

# Copy requirements.txt
COPY ./docker1/requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY ./docker1/predict.py ${LAMBDA_TASK_ROOT} 

# Copy predictors and models folders
COPY ./docker1/subfolder ${LAMBDA_TASK_ROOT}/subfolder

# Set the CMD to your handler
CMD [ "predict.handler" ]